"""Customer Portal bridge contract metadata."""

from __future__ import annotations

from typing import Any

CUSTOMER_FEEDBACK_TYPES = ("tracking", "resource", "quality", "general")
CUSTOMER_FEEDBACK_PRIORITIES = ("normal", "high", "urgent")


def portal_customer_feedback_form_contract() -> dict[str, Any]:
    return {
        "submit_endpoint": "/api/v1/portal/customer/feedback",
        "submit_method": "POST",
        "allowed_feedback_types": list(CUSTOMER_FEEDBACK_TYPES),
        "allowed_priorities": list(CUSTOMER_FEEDBACK_PRIORITIES),
        "requires_order_id": False,
        "customer_name_required": False,
        "customer_email_required": False,
        "resolution_time_promised": False,
        "customer_notified": False,
        "automatic_reply_sent": False,
    }


def portal_customer_endpoints() -> dict[str, str]:
    return {
        "manifest": "/api/v1/portal/customer/manifest",
        "products": "/api/v1/portal/customer/products",
        "orders": "/api/v1/portal/customer/orders",
        "order_detail": "/api/v1/portal/customer/orders/{order_id}",
        "order_snapshot": "/api/v1/portal/customer/orders/{order_id}/snapshot",
        "production": "/api/v1/portal/customer/orders/{order_id}/production",
        "shipment": "/api/v1/portal/customer/orders/{order_id}/shipment",
        "resources": "/api/v1/portal/customer/orders/{order_id}/resources",
        "feedback": "/api/v1/portal/customer/feedback",
    }


def portal_customer_connection_guide(
    *,
    public_base_url: str | None,
    token_required: bool,
    token_configured: bool,
    allowed_origins: list[str],
    include_environment: bool = False,
) -> dict[str, Any]:
    endpoints = portal_customer_endpoints()
    smoke_sequence = [
        {
            "key": "manifest",
            "method": "GET",
            "path": endpoints["manifest"],
            "expected_status": 200,
            "uses_order_id_from": None,
            "mutates_data": False,
        },
        {
            "key": "products",
            "method": "GET",
            "path": endpoints["products"],
            "expected_status": 200,
            "uses_order_id_from": None,
            "mutates_data": False,
        },
        {
            "key": "orders",
            "method": "GET",
            "path": endpoints["orders"],
            "expected_status": 200,
            "uses_order_id_from": None,
            "mutates_data": False,
        },
        {
            "key": "order_snapshot",
            "method": "GET",
            "path": endpoints["order_snapshot"],
            "expected_status": 200,
            "uses_order_id_from": "orders.items[0].id",
            "mutates_data": False,
        },
        {
            "key": "production",
            "method": "GET",
            "path": endpoints["production"],
            "expected_status": 200,
            "uses_order_id_from": "orders.items[0].id",
            "mutates_data": False,
        },
        {
            "key": "shipment",
            "method": "GET",
            "path": endpoints["shipment"],
            "expected_status": 200,
            "uses_order_id_from": "orders.items[0].id",
            "mutates_data": False,
        },
        {
            "key": "resources",
            "method": "GET",
            "path": endpoints["resources"],
            "expected_status": 200,
            "uses_order_id_from": "orders.items[0].id",
            "mutates_data": False,
        },
        {
            "key": "feedback_test",
            "method": "POST",
            "path": endpoints["feedback"],
            "expected_status": 201,
            "uses_order_id_from": "orders.items[0].id optional",
            "mutates_data": True,
            "test_only": True,
            "subject_prefix": "TEST",
        },
    ]
    guide: dict[str, Any] = {
        "consumer": "service.intelli-opus.com",
        "public_base_url": public_base_url,
        "auth": {
            "header_name": "X-Portal-Customer-Token",
            "authorization_bearer_supported": True,
            "required": token_required,
            "configured": token_configured,
            "value_exposed": False,
        },
        "allowed_origins": allowed_origins,
        "smoke_sequence": smoke_sequence,
        "safety": {
            "server_to_server_only": True,
            "browser_token_storage_allowed": False,
            "customer_visible_fields_only": True,
            "planned_dates_are_guarantees": False,
            "feedback_test_creates_ticket": True,
            "automatic_reply_sent": False,
            "customer_notified": False,
            "supplier_notified": False,
            "carrier_api_called": False,
            "deployment_triggered": False,
            "staging_validated": False,
            "token_value_exposed": False,
        },
    }
    if include_environment:
        guide["required_environment"] = [
            {
                "name": "PORTAL_CUSTOMER_API_ENABLED",
                "required_value": "true",
                "configured": True,
                "sensitive": False,
                "value_exposed": True,
            },
            {
                "name": "PORTAL_CUSTOMER_API_TOKEN",
                "required_value": "secret server-to-server value",
                "configured": token_configured,
                "sensitive": True,
                "value_exposed": False,
            },
            {
                "name": "PORTAL_CUSTOMER_ALLOWED_ORIGINS",
                "required_value": "https://service.intelli-opus.com",
                "configured": bool(allowed_origins),
                "sensitive": False,
                "value_exposed": True,
            },
            {
                "name": "PUBLIC_BASE_URL",
                "required_value": "public HTTPS PartnerOS staging origin",
                "configured": bool(public_base_url),
                "sensitive": False,
                "value_exposed": bool(public_base_url),
            },
        ]
    return guide


def portal_customer_field_contract() -> dict[str, Any]:
    return {
        "envelope": ["ok", "data", "error", "request_id"],
        "pagination": ["items", "total", "page", "limit"],
        "products": [
            "id",
            "internal_sku",
            "product_name",
            "product_category",
            "product_family",
            "description",
            "status",
            "uom",
            "currency",
            "default_incoterm",
            "image_url",
            "attributes",
        ],
        "order_summary": [
            "id",
            "order_number",
            "status",
            "order_date",
            "company_id",
            "company_name",
            "currency",
            "grand_total",
            "customer_confirmed_at",
            "ship_to_company",
            "ship_to_address",
        ],
        "order_detail": [
            "bill_to_company",
            "ship_to_name",
            "payment_terms",
            "shipping_terms",
            "customer_notes",
            "line_items",
        ],
        "line_item": [
            "id",
            "product_name",
            "product_category",
            "description",
            "quantity",
            "uom",
            "unit_price",
            "total_price",
            "currency",
            "incoterm",
            "status",
        ],
        "snapshot": [
            "order",
            "customer_status",
            "tracking_summary",
            "portal_display",
            "links",
            "production",
            "shipment",
            "resources",
            "feedback",
            "safety",
        ],
        "tracking_summary": [
            "stage",
            "production_item_count",
            "shipment_item_count",
            "resource_visible_count",
            "feedback_open_count",
            "has_production_updates",
            "has_active_shipment",
            "has_visible_resources",
            "has_open_feedback",
            "planned_dates_are_guarantees",
        ],
        "portal_display": [
            "headline",
            "stage",
            "stage_label",
            "current_step_label",
            "next_action_label",
            "next_action_detail",
            "progress_percent",
            "status_badges",
            "signal_cards",
            "feedback_cta",
            "planned_dates_are_guarantees",
        ],
        "portal_display_status_badge": ["key", "label", "state", "active", "date", "planned_dates_are_guarantees"],
        "portal_display_signal_card": ["key", "label", "active", "count"],
        "portal_display_feedback_cta": [
            "label",
            "path",
            "customer_notified",
            "automatic_reply_sent",
            "resolution_time_promised",
        ],
        "snapshot_links": [
            "order_detail",
            "order_snapshot",
            "production",
            "shipment",
            "resources",
            "feedback_submit",
        ],
        "customer_status": [
            "stage",
            "label",
            "next_action_label",
            "next_action_detail",
            "order_confirmed",
            "production_started",
            "production_completed",
            "ready_to_ship",
            "shipped",
            "delivered",
            "current_step_index",
            "progress_steps",
            "planned_dates_are_guarantees",
        ],
        "customer_next_action": ["next_action_label", "next_action_detail"],
        "customer_status_stages": [
            "pending_confirmation",
            "confirmed",
            "in_production",
            "ready_to_ship",
            "shipped",
            "delivered",
            "cancelled",
        ],
        "progress_step_states": ["complete", "current", "pending"],
        "production_item": ["milestone_type", "milestone_label", "sequence", "status", "planned_date", "actual_date"],
        "shipment_item": [
            "id",
            "status",
            "shipment_method",
            "carrier_name",
            "tracking_number",
            "tracking_url",
            "estimated_ship_date",
            "actual_ship_date",
            "estimated_arrival_date",
            "actual_arrival_date",
        ],
        "resource_item": ["id", "title", "category", "status", "filename", "mime", "size", "download_url", "created_at"],
        "feedback_create": [
            "order_id",
            "company_id",
            "feedback_type",
            "subject",
            "message",
            "priority",
            "customer_name",
            "customer_email",
        ],
        "feedback_snapshot": [
            "submit_endpoint",
            "submit_method",
            "allowed_feedback_types",
            "allowed_priorities",
            "requires_order_id",
            "customer_name_required",
            "customer_email_required",
            "resolution_time_promised",
            "total_count",
            "open_count",
            "customer_notified",
            "automatic_reply_sent",
        ],
        "feedback_create_response": [
            "ticket_number",
            "status",
            "feedback_received",
            "next_links",
            "customer_notified",
            "automatic_reply_sent",
            "resolution_time_promised",
        ],
        "feedback_next_links": [
            "orders",
            "order_snapshot",
            "production",
            "shipment",
            "resources",
            "feedback_submit",
        ],
        "feedback_form_contract": portal_customer_feedback_form_contract(),
        "date_policy": {
            "planned_dates_are_guarantees": False,
            "planned_dates_label": "planned",
            "actual_dates_label": "actual",
        },
    }
