"""Customer Portal bridge contract metadata."""

from __future__ import annotations

from typing import Any

CUSTOMER_FEEDBACK_TYPES = ("tracking", "resource", "quality", "general")
CUSTOMER_FEEDBACK_PRIORITIES = ("normal", "high", "urgent")


def portal_customer_endpoints() -> dict[str, str]:
    return {
        "manifest": "/api/v1/portal/customer/manifest",
        "products": "/api/v1/portal/customer/products",
        "orders": "/api/v1/portal/customer/orders",
        "order_detail": "/api/v1/portal/customer/orders/{order_id}",
        "order_snapshot": "/api/v1/portal/customer/orders/{order_id}/snapshot",
        "production": "/api/v1/portal/customer/orders/{order_id}/production",
        "shipment": "/api/v1/portal/customer/orders/{order_id}/shipment",
        "resources": "/api/v1/portal/customer/orders/{order_id}/resources",
        "feedback": "/api/v1/portal/customer/feedback",
    }


def portal_customer_field_contract() -> dict[str, Any]:
    return {
        "envelope": ["ok", "data", "error", "request_id"],
        "pagination": ["items", "total", "page", "limit"],
        "products": [
            "id",
            "internal_sku",
            "product_name",
            "product_category",
            "product_family",
            "description",
            "status",
            "uom",
            "currency",
            "default_incoterm",
            "image_url",
            "attributes",
        ],
        "order_summary": [
            "id",
            "order_number",
            "status",
            "order_date",
            "company_id",
            "company_name",
            "currency",
            "grand_total",
            "customer_confirmed_at",
            "ship_to_company",
            "ship_to_address",
        ],
        "order_detail": [
            "bill_to_company",
            "ship_to_name",
            "payment_terms",
            "shipping_terms",
            "customer_notes",
            "line_items",
        ],
        "line_item": [
            "id",
            "product_name",
            "product_category",
            "description",
            "quantity",
            "uom",
            "unit_price",
            "total_price",
            "currency",
            "incoterm",
            "status",
        ],
        "snapshot": [
            "order",
            "customer_status",
            "tracking_summary",
            "production",
            "shipment",
            "resources",
            "feedback",
            "safety",
        ],
        "tracking_summary": [
            "stage",
            "production_item_count",
            "shipment_item_count",
            "resource_visible_count",
            "feedback_open_count",
            "has_production_updates",
            "has_active_shipment",
            "has_visible_resources",
            "has_open_feedback",
            "planned_dates_are_guarantees",
        ],
        "customer_status": [
            "stage",
            "label",
            "next_action_label",
            "next_action_detail",
            "order_confirmed",
            "production_started",
            "production_completed",
            "ready_to_ship",
            "shipped",
            "delivered",
            "current_step_index",
            "progress_steps",
            "planned_dates_are_guarantees",
        ],
        "customer_next_action": ["next_action_label", "next_action_detail"],
        "customer_status_stages": [
            "pending_confirmation",
            "confirmed",
            "in_production",
            "ready_to_ship",
            "shipped",
            "delivered",
            "cancelled",
        ],
        "progress_step_states": ["complete", "current", "pending"],
        "production_item": ["milestone_type", "milestone_label", "sequence", "status", "planned_date", "actual_date"],
        "shipment_item": [
            "id",
            "status",
            "shipment_method",
            "carrier_name",
            "tracking_number",
            "tracking_url",
            "estimated_ship_date",
            "actual_ship_date",
            "estimated_arrival_date",
            "actual_arrival_date",
        ],
        "resource_item": ["id", "title", "category", "status", "filename", "mime", "size", "download_url", "created_at"],
        "feedback_create": [
            "order_id",
            "company_id",
            "feedback_type",
            "subject",
            "message",
            "priority",
            "customer_name",
            "customer_email",
        ],
        "feedback_snapshot": [
            "submit_endpoint",
            "submit_method",
            "allowed_feedback_types",
            "allowed_priorities",
            "requires_order_id",
            "customer_name_required",
            "customer_email_required",
            "resolution_time_promised",
            "total_count",
            "open_count",
            "customer_notified",
            "automatic_reply_sent",
        ],
        "feedback_create_response": [
            "ticket_number",
            "status",
            "feedback_received",
            "customer_notified",
            "automatic_reply_sent",
            "resolution_time_promised",
        ],
        "date_policy": {
            "planned_dates_are_guarantees": False,
            "planned_dates_label": "planned",
            "actual_dates_label": "actual",
        },
    }
